version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_dcs
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pklub2025sukses
    volumes:
      - data_dcs:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    networks:
      - network_dcs
      
  rtsp_app:
    build:
      context: ./rtsp_app
      dockerfile: Dockerfile
    container_name: rtsp_app
    volumes:
      - data_dcs:/data/db
    restart: always
    networks:
      - network_dcs

  tuya_app:
    build:
      context: ./tuya_app
      dockerfile: Dockerfile
    container_name: tuya_app
    volumes:
      - data_dcs:/data/db
    restart: always
    networks:
      - network_dcs
    
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - data_dcs:/data/db
    restart: always
    networks:
      - network_dcs

volumes:
  data_dcs:
    driver: local

networks:
  network_dcs:
